spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # Route vers Agriculteur Service
        - id: agriculteur-service
          uri: lb://agriculteur-service
          predicates:
            - Path=/api/agriculteurs/**
          
        # Route vers Equipement Service
        - id: equipement-service
          uri: lb://equipement
          predicates:
            - Path=/api/equipements/**
          
        # Route vers Supervision Service
        - id: supervision-service
          uri: lb://supervision-service
          predicates:
            - Path=/api/supervision/**
      
      # Configuration CORS
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            
      # Configuration des timeouts
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s

# Configuration du serveur
server:
  port: 8888

# Message de configuration
config:
  message: "Gateway Service - Configuration from Git Repository"

# Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9095/eureka

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,refresh
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO
    com.agriculture.gateway: INFO
