spring:
  application:
    name: My-gateway
  cloud:
    gateway:
      routes:
        # Route 1 : Agriculteur Service
        - id: agriculteur-service
          uri: lb://agriculteur-service
          predicates:
            - Path=/api/agriculteurs/**
          
        # Route 2 : Equipement Service
        - id: equipement-service
          uri: lb://equipement
          predicates:
            - Path=/api/equipements/**
          
        # Route 3 : Supervision Service
        - id: supervision-service
          uri: lb://supervision-service
          predicates:
            - Path=/api/supervision/**
      
      # Configuration CORS
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

# Configuration du serveur
server:
  port: 8888

# Message de test
config:
  message: "Gateway Service - Configuration depuis Git"

# Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9095/eureka

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,refresh,routes
  endpoint:
    health:
      show-details: always
    gateway: true
    
