# Configuration pour le service Gateway
spring:
  application:
    name: gateway
  
  # IMPORTANT: Définir le type d'application comme réactive
  main:
    web-application-type: reactive
  
  # Configuration Cloud Gateway
  cloud:
    gateway:
      # Configuration des routes manuelles
      routes:
        # Route 1: Service Agriculteur
        - id: agriculteur-service
          uri: lb://AGRICULTEUR-SERVICE
          predicates:
            - Path=/api/agriculteurs/**
          filters:
            - StripPrefix=1
            - name: Retry
              args:
                retries: 3
                methods: GET,POST
                series: SERVER_ERROR
        
        # Route 2: Service Equipement
        - id: equipement-service
          uri: lb://EQUIPEMENT-SERVICE
          predicates:
            - Path=/api/equipements/**
          filters:
            - StripPrefix=1
        
        # Route 3: Service Supervision
        - id: supervision-service
          uri: lb://SUPERVISION-SERVICE
          predicates:
            - Path=/api/supervision/**
          filters:
            - StripPrefix=1
        
        # Route de test
        - id: test-route
          uri: http://httpbin.org:80
          predicates:
            - Path=/test/**
      
      # Configuration CORS
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            max-age: 3600

# Port du serveur
server:
  port: 8888

# Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9095/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes,refresh
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
    routes:
      enabled: true

# Logging
logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO
    com.netflix.eureka: INFO
